### Register
POST https://localhost:3001/api/auth/register
Content-Type: application/json
AdminPassword: admin

{
    "email": "admin1@example.com",
    "password": "password123",
    "displayName": "Player Admin",
    "playerColor": "#ff000"
}

### Login
POST https://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "player1@example.com",
    "password": "password123"
}

### Login admin
POST https://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "admin6@example.com",
    "password": "password123"
}

### My Profile
GET https://localhost:3001/api/profiles/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmI4N2MyMC03MjQ3LTQwOTktYmI4ZC01ZDk0NjJjMzZhNTUiLCJpYXQiOjE3ODcyMzk5MTksImV4cCI6MTc4NzI0MzUxOX0.pNa7szAYJvEfb-W02cqqmj9U6Y7vjVFPBYoRgpaCqK4

### Change Color
PATCH https://localhost:3001/api/profiles/me/color
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmI4N2MyMC03MjQ3LTQwOTktYmI4ZC01ZDk0NjJjMzZhNTUiLCJpYXQiOjE3ODcyMzk5MTksImV4cCI6MTc4NzI0MzUxOX0.pNa7szAYJvEfb-W02cqqmj9U6Y7vjVFPBYoRgpaCqK4

{
    "playerColor": "fff2222"
}

### Get users (admin)
GET https://localhost:3001/api/auth/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmI4N2MyMC03MjQ3LTQwOTktYmI4ZC01ZDk0NjJjMzZhNTUiLCJpYXQiOjE3ODcyMzQyMjgsImV4cCI6MTc4NzIzNzgyOH0.kFRC1ogqtvQFMDmgXE44xUJfkHjHZoY-IOaudkuWFfs

### Get profiles (admin)
GET https://localhost:3001/api/profiles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmI4N2MyMC03MjQ3LTQwOTktYmI4ZC01ZDk0NjJjMzZhNTUiLCJpYXQiOjE3ODcyMzgwODksImV4cCI6MTc4NzI0MTY4OX0.BbD2o-z1T3Ol6fFTPAd1M8DnAQV56hK-wwu-GLI0vXw


### Delete user and profile (admin)
DELETE https://localhost:3001/api/auth/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmI4N2MyMC03MjQ3LTQwOTktYmI4ZC01ZDk0NjJjMzZhNTUiLCJpYXQiOjE3ODcyMzgwODksImV4cCI6MTc4NzI0MTY4OX0.BbD2o-z1T3Ol6fFTPAd1M8DnAQV56hK-wwu-GLI0vXw

{
    "email": "admin1@example.com"
}